do test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -40,5 +40,12 @@ build-binaries:
 run-tests:
   stage: test
   script:
-    - echo all good
+    - |
+      LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server:$LD_LIBRARY_PATH stack exec app > out
+      if [ `cat out` == "1.2345" ] ; then
+         echo "success";
+      else
+         echo "failed, got" `cat out`;
+         exit 1;
+      fi
 
